<?php
/**
 * @file
 * Code for the CA News feature.
 */
include_once('ca_news.features.inc');

/**
 * Implements hook_menu()
 */
function ca_news_menu() {
  $items['admin/config/worx_features/news'] = array(
    'title' => 'News Configuration',
    'description' => 'Override settings for ca_news',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_news_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_news.admin.inc',
    'file path' => drupal_get_path('module', 'ca_news'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/worx_features/news/general'] = array(
    'title' => 'General Settings',
    'description' => 'Override settings for ca_news',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_news_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_news.admin.inc',
    'file path' => drupal_get_path('module', 'ca_news'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * implements hook_menu_alter().
 */
function ca_news_menu_alter(&$items) {
  $items['news']['title'] = variable_get('ca_news_menu_title', 'News');
}

/**
 * Implements hook_panels_pre_render().
 */
function ca_news_panels_pre_render($panel, $renderer) {
  if (isset($panel->content['new-7']) && $panel->content['new-7']->subtype == 'ca_news-ca_news_list_1') {
    $panel->title = variable_get('ca_news_panel_title', 'News');
  }
}

/**
 * Implements hook_views_pre_render().
 */
function ca_news_views_pre_view(&$view, &$display_id, &$args) {
  if ($display_id == 'ca_news_list_1') {
    $view->set_items_per_page(variable_get('ca_news_list_count', 5));
  }
  if ($display_id == 'ca_news_block_1') {
    $view->set_items_per_page(variable_get('ca_news_block_count', 1));
  }
}